### ISSUE TITLE
apt update doesn't work on 3.6

### ISSUE THREAD

**Issue by tomds** [joyzoursky/docker-python-chromedriver#11]
If I do `apt update` on python-chromedriver:3.6, I get:

```
Err http://deb.debian.org jessie-updates/main amd64 Packages                                                                                                                                             
  404  Not Found
Fetched 10.1 MB in 6s (1644 kB/s)                                                                                                                                                                        
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I  presume this is because Debian Jessie has lost some support due to being an old version.

If I build the image manually, it uses Debian Stretch and works fine, so presumably the underlying python:3.6 image has been upgraded to Stretch since the image on Docker Hub was built.

Any chance of you publishing a freshly-built image of python-chromedriver:3.6 on Docker Hub please?

**Comment by joyzoursky** [comment]
Thanks for your report. Just rebuilt, please try again.

**Comment by tomds** [comment]
It works again now - thanks so much! ❤️
