### ISSUE TITLE
noob question about xvfb

### ISSUE THREAD

**Issue by ErichBSchulz** [joyzoursky/docker-python-chromedriver#4]
thanks for this repo.

sorry I'm new to automated selenium - but I'm curious about what the value of xvfb is?

are you able to indicate what it's inclusion gives?

**Comment by joyzoursky** [comment]
xvfb is used to run the tests on browser headlessly before there is official headless mode released by Chrome or Firefox or else. ref: http://elementalselenium.com/tips/38-headless
as some people maybe still using the old images with xvfb so i just keep them in the repository.
